name: Create Tag on Push

on:
  push:
    branches:
      - main  # 你可以将这里改为你需要的分支

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get current date
      id: get_date
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create and push tag
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git tag ${{ env.DATE }}
        git push --force origin ${{ env.DATE }}
